### ISSUE TITLE
Typewriter animations

### ISSUE THREAD

**Issue by mwolff3** [lsu-emdm/nexusUI#20]
Hey so pressing 'v' lights up a key on the bottom right of the iinterface.

Also my ALT key doesn't do anyting, nor do some of the punctuation marks. (comma, period, and regular slash). 

Running Chrome on Windows 8.1. Not sure if that helps.

**Comment by taylorbf** [comment]
The dev branch now has fixes for the following keys:

v
down
right
tab
,
.
/

These are all tested on Mac, untested on Windows. 

I have not added system keys such as option or alt... I'm currently leaning toward not supporting them because using them because they are tied into other system actions.
