### ISSUE TITLE
Envelope - apply as an animation to some parameter

### ISSUE THREAD

**Issue by jesseallison** [lsu-emdm/nexusUI#23]
There should be a way to apply an envelope to a parameter or js variable and then trigger it when wanted.

**Comment by taylorbf** [comment]
If you start the envelope

```js
envelope1.duration = 1000   // 1000ms duration
envelope1.looping = true
envelope1.start()
````

it will output continuous amplitude values as it cycles through its envelope function. These can be used with a common NexusUI event listener

```js
envelope1.on('amp',function(data) {
     synth.amp = data
})
```

It seems more consistent to use our usual event listener `.on()`, and more flexible, rather than designing a new API for applying/connecting widgets & variables. That's my impression, anyway?
