### ISSUE TITLE
Set initial value for slider

### ISSUE THREAD

**Issue by jllodra** [lsu-emdm/nexusUI#30]
Hi, I'm making some experiments with this interesting library,
but I can't get to set an initial value for a Slider, which is frustrating.

```
nx.onload = function() {
  slider1.val = 0.40;
  // also tried:
  // slider1.value = 0.40;
  // slider1.init();
  // slider1.draw();
};
```

**Comment by jllodra** [comment]
Finally found a way:

```
		slider1.set({
			value: 0.40
		});
```

**Comment by taylorbf** [comment]
Using `.set()` is the recommended way

```js
nx.onload = function() {
   slider1.set({ value: 0.4 })
}
```

It is nicer because it also calls .draw() on the widget.

To edit .val directly, what you were looking for is:

```
slider1.val.value = 0.4
```

**Comment by jllodra** [comment]
Thank you :)

**Comment by jesseallison** [comment]
This has gotten a lot more convoluted than in the past. Is there a reason for putting all updates of parameters into a .set() command?  This is good for doing hash setting of many parameters - especially clear at setup.  However it makes regular usage of the instances rather convoluted and a lot more typing and syntax to deal with.

Can we update it to accept both?

slider1.value = 0.4;
slider1.set({ value: 0.4 });

Jesse

**Comment by taylorbf** [comment]
Yes, you can still do this!

```
slider1.val.value = 0.4
slider1.draw()
```

.set() was created for a few things

 - networked interfaces (it is nice to be able to pass the .val object through the net and easily set remote widgets)
 - it removes the necessity of calling .draw() after setting a value, which some users would forget to do
 - it lets users ignore the tedium of .val.value

I do think .set() was a product of moving from position1.x to position1.val.x

.val was created so that all of a widget's actionable / interactive properties would be in one JS object. Our use of .val has been good for development, less so for API usability. The new *ghost* gesture recorder, for example, can ping a widget's .val and receive a perfect picture of that interface's current state.

.val looks redundance with slider and dial because of the slider1.val.value situation, yes. It is more clear with position1.val.x and position1.val.y. There are other options that we have, with a bit of refactoring, so this should be a discussion item for us soon!

**Comment by jesseallison** [comment]
Ahh yes, I remember now. Let’s close this thread and start another dev item to take a look at this.  I bet there’s a way to allow both approaches. Perhaps even making a .value(0.4) function that sets and redraws automatically.

In other programming languages this is managed by getter and setter methods (often times automatically synthesized) with no direct access to the parameter in the instance.
