### ISSUE TITLE
Local Docs Generation script

### ISSUE THREAD

**Issue by jesseallison** [lsu-emdm/nexusUI#4]
Look into script to generate local documentation.  Add to .gitignore so that it doesnt get uploaded.

**Comment by taylorbf** [comment]
If you download the nexusUI repository, and open the website in the /api folder, it will permanently show you documentation for your downloaded version of nexusUI, even if the version on github changes.

The website in /api links to your local api markdown files and local nexusui.js, meaning it will always be accurate to the build you've downloaded.

However, you must load the /api website on a server, because our documentation relies on API calls to flatdoc.
