### ISSUE TITLE
multislider acces value list

### ISSUE THREAD

**Issue by AKa-visuals** [lsu-emdm/nexusUI#53]
Hello! first say that nexus is a great thing, really love it!
Actually im developing a ui editor based in vvvv http://vvvv.org/
already get it working with most of the widgets.
but actually i have problems to acces the multislider list data.
I tried to acces the array and convert it to string, but no good result.
this is the function:
multislider1.on('*',function(data)  {
var a = data.slice(0);
var b= a.toString();
if ("vvvv" in window) vvvv.multislider1(b);
})
what im doing wrong?
another issue is to set the Osc to work in an upload ui in a website ,,,how can i set the ip and transmit the osc?
thanks

**Comment by taylorbf** [comment]
Hi there @AKa-visuals. Very cool that you are making a UI editor with this. Please share a preview when you get it up and running!

To access a list of all the values in the multislider, use **data.list**. However, I just checked the code and this is an object, not an array, which I believe is a bug because the documentation says it should be an array. I have just merged a round of updates to the master branch of NexusUI. In this update, I have made sure that the multislider's data.list is always an array. So with the latest version of nexusUI, you could do:

```
multislider1.on('*',function(data) {
  var a = data.list.slice(0);
  var b= a.toString();
  if ("vvvv" in window) vvvv.multislider1(b);
})
```

As for your OSC question ... Do you mean you wish to have a website on the web send OSC to a specific IP? That is a bit more tricky... The demo we provide works within a local network -- i.e. you would host your nexusUI page on localhost and send to another IP on the same network. OSC communication from a website to a specific IP is not really in my bag of tricks. Perhaps someone else can chime in on this.

**Comment by AKa-visuals** [comment]
allright now it works , thanks a lot, i just curious about the new design of some widgets, there are no round edges more? 
another thing is about the dial and slider that now includes de data output, is anyway to disable, ??
i think its better to deal with that apart in your document so you can choose to use the data out, transform it and then show it or not.
About OSC , so what the way to use it in an ipad or phone?
Thanks and i will show you the release of my editor.

**Comment by taylorbf** [comment]
Widgets are now square by default. You can quite easily add round edges globally:

```
canvas {
   border-radius:5px;
   -webkit-border-radius:5px; /* not sure if this is still necessary */
   -moz-border-radius:5px; /* not sure if this is still necessary */
}
```

For data output -- yes, there should be a way to turn it off. I'll add that with the next update. NexusUI is used by a wide range of users with varying levels of experience. Having built-in value feedback has been a common request. But yes it should be optional.

Check out the [OSC demo](https://github.com/lsu-emdm/nx-AjaxDemo) for mobile device communication.
